name: Deploy Nuxt site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DOWNLOADER_DIR: scrapbox-downloader
  NUXT_BLOG_DIR: scrapbox-nuxt-blog
  SCRAPBOX_PROJECT_NAME: ${{ vars.SCRAPBOX_PROJECT_NAME }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ env.NUXT_BLOG_DIR }}/package-lock.json
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: nuxt
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.NUXT_BLOG_DIR }}/.output/public
            ${{ env.NUXT_BLOG_DIR }}/.nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-
      # downloader
      - name: Make directories
        run: |
          mkdir ${{ env.DOWNLOADER_DIR }}/content
          mkdir ${{ env.NUXT_BLOG_DIR }}/content
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.DOWNLOADER_DIR }}
      - name: Download blog content
        run: node index.js ${{ vars.SCRAPBOX_PROJECT_NAME }} ${{ vars.SCRAPBOX_CONNECT_SID }}
        working-directory: ${{ env.DOWNLOADER_DIR }}
      - name: Move blog content
        run: mv ${{ env.DOWNLOADER_DIR }}/content/ ${{ env.NUXT_BLOG_DIR }}/content/
      # nuxt-blog
      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.NUXT_BLOG_DIR }}
      - name: Static HTML export with Nuxt
        run: npm run generate
        working-directory: ${{ env.NUXT_BLOG_DIR }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.NUXT_BLOG_DIR }}/.output/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
